# 日志级别可选: off, trace, debug, info, warning, error, critical。
[log.modules]
zlm = "off"
srt = "off"
ffmpeg = "off"
streamer = "info"
processor = "info"

[log.console]
enabled = true
color = true
level = "trace"

[log.rotating_file]
enabled = false
path = "./logs/mw-streamer.log"
level = "trace"
max_file_size = 10485760
max_files = 5

[log.async]
enabled = false
queue_size = 8192
# 可选: block, overrun_oldest。
overflow = "overrun_oldest"

[zlm]
# 0表示由ZLToolKit根据CPU核心数决定线程数。
event_poller_threads = 0
work_threads = 0
enable_cpu_affinity = true
