set(MW_STREAMER_TEST_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")
set(MW_STREAMER_TEST_DATA_DIR "${MW_STREAMER_TEST_ROOT}/data")

add_subdirectory(api)
add_subdirectory(config)
add_subdirectory(processor)
add_subdirectory(media)
add_subdirectory(pipeline)
add_subdirectory(io)
add_subdirectory(runtime)
add_subdirectory(e2e)
